# SSL برای superhesab.ir و *.superhesab.ir — Let's Encrypt YR2
ssl_certificate /etc/ssl/superhesab.ir/fullchain.pem;
ssl_certificate_key /etc/ssl/superhesab.ir/privkey.pem;
include /etc/letsencrypt/options-ssl-nginx.conf;
ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
